---

- name: Install influxdb
  include: "install-{{ ansible_os_family|lower }}.yml"

- name: Create influxdb config file
  template:
    src:   influxdb.conf.j2
    dest:  /etc/influxdb/influxdb.conf
    owner: root
    group: root
    mode:  0644
  notify: Restart influxdb

- name: Create influxdb service startup config file
  template:
    src:   etc.default.influxdb.j2
    dest:  /etc/default/influxdb
    owner: root
    group: root
    mode:  0644
  notify: Restart influxdb

- name: Create influxdb logrotate config
  template:
    src:   influxdb.logrotate.j2
    dest:  /etc/logrotate.d/influxdb
    owner: root
    group: root
    mode:  0644

- name: Start influxdb
  service: name=influxdb enabled=yes state=started
